---
  extends: "airbnb-base"
  parser: "babel-eslint"
  plugins:
    - "react"
  ecmaFeatures:
    jsx: true
    modules: true
    arrowFunctions: true
  include: "./src/"
  rules:
    class-methods-use-this:
      - 0
      - exceptMethods:
        - "foo"
        - "render"
    react/jsx-no-undef: 1
    react/jsx-uses-react: 1
    react/jsx-uses-vars: 1
